-- schema.sql — full reference schema for a fresh install.
-- Generated by concatenating database/migrations/*.sql (source of truth).
-- The Migration runner (src/Database/Migration.php) applies those files
-- individually and tracks them in schema_migrations; this file is for
-- documentation and manual bootstrapping only.

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration VARCHAR(191) NOT NULL PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 001_core_tables.sql =====
-- Core: admins, bot users, global settings, and the generic text/entity store.

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL,
    username VARCHAR(64) NULL,
    role ENUM('super_admin', 'admin') NOT NULL DEFAULT 'admin',
    added_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_admins_telegram_user_id (telegram_user_id),
    CONSTRAINT fk_admins_added_by FOREIGN KEY (added_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL,
    username VARCHAR(64) NULL,
    first_name VARCHAR(128) NULL,
    language_code VARCHAR(16) NULL,
    is_blocked TINYINT(1) NOT NULL DEFAULT 0,
    first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_users_telegram_user_id (telegram_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Database-driven runtime configuration (scanner thresholds, mode, cooldowns, ...).
-- Seeded from .env defaults on first boot; editable afterwards from the admin panel.
-- value_type tells the SettingsManager how to cast setting_value back to PHP.
CREATE TABLE IF NOT EXISTS bot_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NULL,
    value_type ENUM('string', 'int', 'float', 'bool', 'json') NOT NULL DEFAULT 'string',
    updated_by_admin_id BIGINT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bot_settings_key (setting_key),
    CONSTRAINT fk_bot_settings_admin FOREIGN KEY (updated_by_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Every user-facing string in the bot (welcome text, signal wording, button
-- labels, error messages, ...) lives here instead of being hard-coded in
-- PHP. `entities` stores the raw Telegram MessageEntity[] JSON so premium
-- custom emoji / bold / spoilers survive round-tripping through the editor
-- (text is never reduced to Markdown, which would drop them).
CREATE TABLE IF NOT EXISTS text_formats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    text_key VARCHAR(128) NOT NULL,
    text_value TEXT NOT NULL,
    entities JSON NOT NULL,
    parse_mode VARCHAR(16) NULL,
    reply_to_message_id BIGINT NULL,
    quote_text TEXT NULL,
    quote_entities JSON NULL,
    quote_position INT UNSIGNED NULL,
    updated_by_admin_id BIGINT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_text_formats_key (text_key),
    CONSTRAINT fk_text_formats_admin FOREIGN KEY (updated_by_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 002_exchanges_symbols.sql =====
-- Exchanges, the dynamic symbol universe, live market snapshots, and candles.

CREATE TABLE IF NOT EXISTS exchanges (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(32) NOT NULL COMMENT 'binance, mexc, wallex, ... — matches config/exchanges.php key',
    name VARCHAR(64) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    status ENUM('online', 'degraded', 'offline') NOT NULL DEFAULT 'online',
    last_error TEXT NULL,
    last_checked_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_exchanges_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Free-form runtime overrides per exchange (rate limits, ws toggles, ...),
-- editable from the admin panel without redeploying config/exchanges.php.
CREATE TABLE IF NOT EXISTS exchange_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    exchange_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_exchange_settings (exchange_id, setting_key),
    CONSTRAINT fk_exchange_settings_exchange FOREIGN KEY (exchange_id) REFERENCES exchanges (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The tradeable universe as reported by each exchange. Rebuilt/refreshed by
-- the scanner; NOT a fixed list of 200 rows — `is_in_universe` + `rank`
-- (in market_data) are what the scanner actually filters on.
CREATE TABLE IF NOT EXISTS symbols (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    exchange_id BIGINT UNSIGNED NOT NULL,
    symbol VARCHAR(32) NOT NULL COMMENT 'exchange-native symbol, e.g. BTCUSDT',
    base_asset VARCHAR(16) NOT NULL,
    quote_asset VARCHAR(16) NOT NULL,
    market_type ENUM('spot', 'futures') NOT NULL DEFAULT 'spot',
    status ENUM('trading', 'break', 'delisted') NOT NULL DEFAULT 'trading',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    price_precision TINYINT UNSIGNED NULL,
    qty_precision TINYINT UNSIGNED NULL,
    min_notional DECIMAL(24, 8) NULL,
    last_seen_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_symbols_exchange_symbol (exchange_id, symbol),
    KEY idx_symbols_quote_active (quote_asset, is_active),
    CONSTRAINT fk_symbols_exchange FOREIGN KEY (exchange_id) REFERENCES exchanges (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Latest ticker/liquidity snapshot per symbol — one row per symbol, upserted
-- on every scan. This (not a history table) is what the universe filter
-- (volume/liquidity/spread ranking -> Top N) reads.
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    price DECIMAL(24, 12) NOT NULL DEFAULT 0,
    volume_24h DECIMAL(28, 8) NOT NULL DEFAULT 0,
    quote_volume_24h DECIMAL(28, 8) NOT NULL DEFAULT 0,
    price_change_percent_24h DECIMAL(10, 4) NOT NULL DEFAULT 0,
    high_24h DECIMAL(24, 12) NOT NULL DEFAULT 0,
    low_24h DECIMAL(24, 12) NOT NULL DEFAULT 0,
    spread_percent DECIMAL(10, 6) NOT NULL DEFAULT 0,
    trades_count_24h BIGINT UNSIGNED NULL,
    volatility DECIMAL(10, 6) NULL COMMENT 'e.g. ATR% of price, filled in by VolumeAnalyzer',
    liquidity_score DECIMAL(10, 4) NULL,
    volume_rank INT UNSIGNED NULL COMMENT 'rank within its exchange for the current scan',
    is_in_universe TINYINT(1) NOT NULL DEFAULT 0,
    captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_market_data_symbol (symbol_id),
    KEY idx_market_data_universe (is_in_universe, volume_rank),
    CONSTRAINT fk_market_data_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OHLCV history per symbol/timeframe. open_time/close_time are epoch
-- milliseconds (matches every exchange kline API directly, no conversion).
CREATE TABLE IF NOT EXISTS candles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    timeframe VARCHAR(4) NOT NULL COMMENT '1m, 5m, 15m, 1h, 4h, 1d, ... not hard-coded elsewhere',
    open_time BIGINT UNSIGNED NOT NULL,
    close_time BIGINT UNSIGNED NOT NULL,
    open DECIMAL(24, 12) NOT NULL,
    high DECIMAL(24, 12) NOT NULL,
    low DECIMAL(24, 12) NOT NULL,
    close DECIMAL(24, 12) NOT NULL,
    volume DECIMAL(28, 8) NOT NULL,
    quote_volume DECIMAL(28, 8) NULL,
    trades_count INT UNSIGNED NULL,
    is_closed TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_candles_symbol_tf_time (symbol_id, timeframe, open_time),
    KEY idx_candles_lookup (symbol_id, timeframe, open_time DESC),
    CONSTRAINT fk_candles_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 003_channels.sql =====
-- Telegram channels the bot posts signals to, each with its own filtering
-- rules and its own signal template (spec #16/#17: Channel A > score 80,
-- Channel B everything, Channel C LONG-only, ...).

CREATE TABLE IF NOT EXISTS signal_templates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    template_text TEXT NOT NULL COMMENT 'raw text with {placeholder} tokens, see SignalFormatter',
    entities JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'MessageEntity[] anchored to template_text, offsets recomputed per render',
    parse_mode VARCHAR(16) NULL,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    reply_to_message_id BIGINT NULL,
    quote_text TEXT NULL,
    quote_entities JSON NULL,
    quote_position INT UNSIGNED NULL,
    created_by_admin_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_signal_templates_admin FOREIGN KEY (created_by_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channels (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chat_id BIGINT NOT NULL COMMENT 'Telegram chat id, negative for channels/supergroups',
    username VARCHAR(64) NULL,
    title VARCHAR(255) NULL,
    type ENUM('channel', 'group', 'supergroup') NOT NULL DEFAULT 'channel',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    language VARCHAR(8) NOT NULL DEFAULT 'fa',
    parse_mode VARCHAR(16) NOT NULL DEFAULT 'HTML',
    signal_template_id BIGINT UNSIGNED NULL COMMENT 'falls back to the is_default template when NULL',
    minimum_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
    direction_filter ENUM('ANY', 'LONG', 'SHORT') NOT NULL DEFAULT 'ANY',
    bot_is_admin TINYINT(1) NOT NULL DEFAULT 0,
    bot_can_post TINYINT(1) NOT NULL DEFAULT 0,
    permissions_checked_at DATETIME NULL,
    added_by_admin_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_channels_chat_id (chat_id),
    KEY idx_channels_enabled (enabled),
    CONSTRAINT fk_channels_template FOREIGN KEY (signal_template_id) REFERENCES signal_templates (id) ON DELETE SET NULL,
    CONSTRAINT fk_channels_admin FOREIGN KEY (added_by_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Free-form per-channel overrides beyond the typed columns above.
CREATE TABLE IF NOT EXISTS channel_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    channel_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_channel_settings (channel_id, setting_key),
    CONSTRAINT fk_channel_settings_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- channel_strategies (channel_id, strategy_id) is created in
-- 004_indicators_strategies.sql, once the `strategies` table it
-- references exists.

-- ===== 004_indicators_strategies.sql =====
-- Indicator plugin registry + cached outputs, and the strategy registry
-- whose scoring rules/confluences are configured here (never hard-coded —
-- see spec #36, filled in once real strategy rules are provided).

CREATE TABLE IF NOT EXISTS indicators (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(32) NOT NULL COMMENT 'EMA, RSI, MACD, ... matches IndicatorInterface::name()',
    name VARCHAR(64) NOT NULL,
    class_name VARCHAR(255) NOT NULL COMMENT 'FQCN implementing App\\Indicators\\IndicatorInterface',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    default_params JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_indicators_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cache of computed indicator output per candle so the engine only computes
-- the newest candles incrementally instead of recalculating full history
-- (spec #41 performance requirement).
CREATE TABLE IF NOT EXISTS indicator_values (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    timeframe VARCHAR(4) NOT NULL,
    indicator_id BIGINT UNSIGNED NOT NULL,
    candle_open_time BIGINT UNSIGNED NOT NULL,
    value JSON NOT NULL,
    computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_indicator_values (symbol_id, timeframe, indicator_id, candle_open_time),
    KEY idx_indicator_values_lookup (symbol_id, timeframe, indicator_id, candle_open_time DESC),
    CONSTRAINT fk_indicator_values_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE,
    CONSTRAINT fk_indicator_values_indicator FOREIGN KEY (indicator_id) REFERENCES indicators (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS strategies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(64) NOT NULL COMMENT 'matches StrategyInterface::code(), e.g. strategy_a',
    name VARCHAR(128) NOT NULL,
    description TEXT NULL,
    class_name VARCHAR(255) NULL COMMENT 'FQCN implementing App\\Strategy\\StrategyInterface, if code-based',
    is_active TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'inactive until real rules are supplied and reviewed',
    htf_timeframe VARCHAR(4) NULL,
    confirmation_timeframe VARCHAR(4) NULL,
    entry_timeframe VARCHAR(4) NULL,
    min_score TINYINT UNSIGNED NOT NULL DEFAULT 75,
    -- STRATEGY CONFIGURATION (spec #36): required confluences, per-factor
    -- score weights, support/resistance/OB/FVG/volume/indicator conditions.
    -- Structure is intentionally open (JSON) — ConfluenceEngine reads it,
    -- nothing in the engine hard-codes weights or thresholds.
    config JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_strategies_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS strategy_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    strategy_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_strategy_settings (strategy_id, setting_key),
    CONSTRAINT fk_strategy_settings_strategy FOREIGN KEY (strategy_id) REFERENCES strategies (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Which strategies are allowed to publish into a given channel (spec #16).
-- Empty for a channel = all active strategies.
CREATE TABLE IF NOT EXISTS channel_strategies (
    channel_id BIGINT UNSIGNED NOT NULL,
    strategy_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (channel_id, strategy_id),
    CONSTRAINT fk_channel_strategies_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE,
    CONSTRAINT fk_channel_strategies_strategy FOREIGN KEY (strategy_id) REFERENCES strategies (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 005_zones.sql =====
-- Price-action structures detected by the Strategy layer: S/R zones
-- (multi-method composite), order blocks, and fair value gaps.

CREATE TABLE IF NOT EXISTS zones (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    timeframe VARCHAR(4) NOT NULL,
    type ENUM('support', 'resistance') NOT NULL,
    high DECIMAL(24, 12) NOT NULL,
    low DECIMAL(24, 12) NOT NULL,
    strength DECIMAL(6, 2) NOT NULL DEFAULT 0,
    touches INT UNSIGNED NOT NULL DEFAULT 0,
    volume DECIMAL(28, 8) NULL,
    methods JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'which detectors contributed: swing_high_low, volume, rejection, clustering, htf_levels, liquidity, prev_high_low',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    invalidated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_zones_lookup (symbol_id, timeframe, is_active),
    CONSTRAINT fk_zones_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_blocks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    timeframe VARCHAR(4) NOT NULL,
    type ENUM('bullish', 'bearish') NOT NULL,
    high DECIMAL(24, 12) NOT NULL,
    low DECIMAL(24, 12) NOT NULL,
    origin_candle_open_time BIGINT UNSIGNED NOT NULL,
    strength DECIMAL(6, 2) NOT NULL DEFAULT 0,
    volume DECIMAL(28, 8) NULL,
    mitigated TINYINT(1) NOT NULL DEFAULT 0,
    mitigated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_order_blocks_lookup (symbol_id, timeframe, mitigated),
    CONSTRAINT fk_order_blocks_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fvgs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    symbol_id BIGINT UNSIGNED NOT NULL,
    timeframe VARCHAR(4) NOT NULL,
    type ENUM('bullish', 'bearish') NOT NULL,
    high DECIMAL(24, 12) NOT NULL,
    low DECIMAL(24, 12) NOT NULL,
    midpoint DECIMAL(24, 12) NOT NULL,
    size DECIMAL(24, 12) NOT NULL,
    origin_candle_open_time BIGINT UNSIGNED NOT NULL,
    filled TINYINT(1) NOT NULL DEFAULT 0,
    partially_filled TINYINT(1) NOT NULL DEFAULT 0,
    filled_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_fvgs_lookup (symbol_id, timeframe, filled),
    CONSTRAINT fk_fvgs_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 006_signals.sql =====
-- The standard Signal object (spec #13), its lifecycle history, and its
-- per-channel Telegram delivery tracking (needed to edit/pin the right
-- message later without re-sending).

CREATE TABLE IF NOT EXISTS signals (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    exchange_id BIGINT UNSIGNED NOT NULL,
    symbol_id BIGINT UNSIGNED NOT NULL,
    strategy_id BIGINT UNSIGNED NULL,
    direction ENUM('LONG', 'SHORT') NOT NULL,
    timeframe VARCHAR(4) NOT NULL,
    entry DECIMAL(24, 12) NOT NULL,
    stop_loss DECIMAL(24, 12) NOT NULL,
    take_profit_1 DECIMAL(24, 12) NULL,
    take_profit_2 DECIMAL(24, 12) NULL,
    take_profit_3 DECIMAL(24, 12) NULL,
    risk_reward DECIMAL(8, 3) NULL,
    score TINYINT UNSIGNED NOT NULL,
    confidence VARCHAR(16) NULL,
    reasons JSON NOT NULL DEFAULT (JSON_ARRAY()),
    zones JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'zone/order-block/FVG ids and snapshots that fed this signal',
    indicators JSON NOT NULL DEFAULT (JSON_OBJECT()) COMMENT 'indicator values at signal time, for later audit',
    fingerprint VARCHAR(191) NOT NULL COMMENT 'exchange+symbol+direction+strategy+zone+timeframe, see SignalCooldown',
    mode ENUM('LIVE', 'DRY_RUN') NOT NULL DEFAULT 'DRY_RUN',
    status ENUM('new', 'active', 'closed', 'cancelled', 'invalidated') NOT NULL DEFAULT 'new',
    close_reason VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    closed_at DATETIME NULL,
    UNIQUE KEY uq_signals_uuid (uuid),
    KEY idx_signals_fingerprint_status (fingerprint, status),
    KEY idx_signals_symbol_created (symbol_id, created_at),
    KEY idx_signals_status (status),
    CONSTRAINT fk_signals_exchange FOREIGN KEY (exchange_id) REFERENCES exchanges (id) ON DELETE CASCADE,
    CONSTRAINT fk_signals_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id) ON DELETE CASCADE,
    CONSTRAINT fk_signals_strategy FOREIGN KEY (strategy_id) REFERENCES strategies (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS signal_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    signal_id BIGINT UNSIGNED NOT NULL,
    event_type ENUM(
        'created', 'sent', 'edited', 'tp1_hit', 'tp2_hit', 'tp3_hit',
        'sl_hit', 'closed', 'cancelled', 'invalidated'
    ) NOT NULL,
    payload JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_signal_events_signal (signal_id, created_at),
    CONSTRAINT fk_signal_events_signal FOREIGN KEY (signal_id) REFERENCES signals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS signal_channel_deliveries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    signal_id BIGINT UNSIGNED NOT NULL,
    channel_id BIGINT UNSIGNED NOT NULL,
    telegram_message_id BIGINT NULL,
    status ENUM('pending', 'sent', 'edited', 'failed') NOT NULL DEFAULT 'pending',
    error TEXT NULL,
    sent_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_signal_channel (signal_id, channel_id),
    CONSTRAINT fk_deliveries_signal FOREIGN KEY (signal_id) REFERENCES signals (id) ON DELETE CASCADE,
    CONSTRAINT fk_deliveries_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 007_operations.sql =====
-- Operational tables: scan history (System Health), DB-mirrored error log
-- (for the in-bot "📋 Logs" viewer — full detail always stays in
-- storage/logs/*.log), and the queue backing the worker's job dispatch.

CREATE TABLE IF NOT EXISTS scanner_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    exchange_id BIGINT UNSIGNED NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    symbols_scanned INT UNSIGNED NOT NULL DEFAULT 0,
    signals_generated INT UNSIGNED NOT NULL DEFAULT 0,
    errors_count INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('running', 'completed', 'failed') NOT NULL DEFAULT 'running',
    notes TEXT NULL,
    KEY idx_scanner_runs_started (started_at),
    CONSTRAINT fk_scanner_runs_exchange FOREIGN KEY (exchange_id) REFERENCES exchanges (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Populated by App\Logger\DatabaseLogHandler for level >= ERROR only, so
-- "Errors Today" in System Health and the Logs admin screen are cheap
-- queries. This is a mirror for the admin UI, not the source of truth —
-- storage/logs/*.log holds every level and full stack traces.
CREATE TABLE IF NOT EXISTS logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR(16) NOT NULL,
    component VARCHAR(64) NOT NULL,
    message TEXT NOT NULL,
    context JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_logs_component_created (component, created_at),
    KEY idx_logs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Database-backed queue (spec #29). Signal dispatch and every outbound
-- Telegram call go through here so a transient Telegram API failure never
-- blocks the scanner loop; queue_worker.php drains this with retry/backoff.
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    queue VARCHAR(64) NOT NULL DEFAULT 'default',
    job_type VARCHAR(128) NOT NULL COMMENT 'FQCN implementing App\\Queue\\JobInterface',
    payload JSON NOT NULL,
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'job is not picked up before this time (backoff delay)',
    reserved_at DATETIME NULL,
    status ENUM('pending', 'reserved', 'done', 'failed') NOT NULL DEFAULT 'pending',
    last_error TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_jobs_pickup (queue, status, available_at),
    KEY idx_jobs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 008_seed_data.sql =====
-- Idempotent seed data: exchange rows, default runtime settings mirroring
-- the .env defaults, default bot texts, and a default signal template.
-- Admins are NOT seeded here (that depends on the deployment's
-- TELEGRAM_ADMIN_IDS and is synced at boot by AdminRepository::syncFromConfig()).

INSERT IGNORE INTO exchanges (code, name, enabled) VALUES
    ('binance', 'Binance', 1),
    ('mexc', 'MEXC', 1),
    ('wallex', 'Wallex', 1);

INSERT IGNORE INTO bot_settings (setting_key, setting_value, value_type) VALUES
    ('mode', 'DRY_RUN', 'string'),
    ('scan_symbol_limit', '200', 'int'),
    ('scan_interval_seconds', '60', 'int'),
    ('min_volume', '100000', 'float'),
    ('min_liquidity', '50000', 'float'),
    ('min_signal_score', '75', 'int'),
    ('signal_cooldown_seconds', '1800', 'int'),
    ('universe_quote_assets', '["USDT","USDC"]', 'json'),
    ('universe_selection', 'top_volume', 'string');

INSERT IGNORE INTO text_formats (text_key, text_value, entities) VALUES
    ('welcome', N'به ربات سیگنال خوش آمدید.', JSON_ARRAY()),
    ('error_permission', N'شما اجازه دسترسی به این بخش را ندارید.', JSON_ARRAY()),
    ('channel_added', N'کانال با موفقیت اضافه شد.', JSON_ARRAY()),
    ('channel_removed', N'کانال حذف شد.', JSON_ARRAY()),
    ('scanner_status', N'وضعیت اسکنر بازار.', JSON_ARRAY()),
    ('signal_long', N'سیگنال خرید (LONG) جدید.', JSON_ARRAY()),
    ('signal_short', N'سیگنال فروش (SHORT) جدید.', JSON_ARRAY());

INSERT IGNORE INTO signal_templates (id, name, template_text, entities, parse_mode, is_default) VALUES
    (1, 'Default', CONCAT(
        '{direction} {symbol}\n',
        '\n',
        'Exchange: {exchange}\n',
        'Entry: {entry}\n',
        'Stop Loss: {stop_loss}\n',
        '\n',
        'TP1: {tp1}\n',
        'TP2: {tp2}\n',
        'TP3: {tp3}\n',
        '\n',
        'Risk/Reward: {risk_reward}\n',
        'Score: {score}/100\n',
        'Timeframe: {timeframe}\n',
        '\n',
        '{reasons}'
    ), JSON_ARRAY(), 'HTML', 1);

-- ===== 009_admin_states.sql =====
-- Lightweight conversation state (FSM) for multi-step admin flows (add
-- channel, edit a text_formats entry, edit a signal template, ...). Each
-- webhook request is a fresh PHP process, so this is what lets a bot
-- "remember" it is waiting for the next message from a given admin.

CREATE TABLE IF NOT EXISTS admin_states (
    telegram_user_id BIGINT NOT NULL PRIMARY KEY,
    state VARCHAR(64) NOT NULL,
    context JSON NOT NULL DEFAULT (JSON_OBJECT()),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== 010_zone_natural_keys.sql =====
-- Order blocks and FVGs are upserted by their natural key on every scan
-- (same symbol/timeframe/type/origin candle = the same structure), so a
-- unique key is needed for INSERT ... ON DUPLICATE KEY UPDATE to work —
-- this also keeps `mitigated`/`filled` sticky across scans instead of
-- being reset by re-detection. Zones have no single origin candle (they
-- are ranges built from several methods), so they stay a replace-active-
-- set-per-scan model and do not need one.

ALTER TABLE order_blocks
    ADD UNIQUE KEY uq_order_blocks_natural (symbol_id, timeframe, type, origin_candle_open_time);

ALTER TABLE fvgs
    ADD UNIQUE KEY uq_fvgs_natural (symbol_id, timeframe, type, origin_candle_open_time);

