//@version=5
indicator("Daily Trade | Multi-Timeframe S/R", shorttitle = "DT MTF S/R", overlay = true, max_lines_count = 500)

extend = input.string(defval = "Both", options = ["Left", "Right", "Both", "None"], title = "Extend Lines")
style  = input.string(defval = "Dotted", title = "Line Style", options = ["Dotted", "Solid", "Dashed"])

min240Show  = input.bool (title = "4 Hour Levels", defval = true, group = "S/R Levels", inline = "1")
min240col   = input.color(title = "",              defval = color.white,  group = "S/R Levels", inline = "1")
min1440Show = input.bool (title = "Daily Levels",  defval = true, group = "S/R Levels", inline = "2")
min1440col  = input.color(title = "",              defval = color.purple, group = "S/R Levels", inline = "2")
minWShow    = input.bool (title = "Weekly Levels", defval = true, group = "S/R Levels", inline = "3")
minWcol     = input.color(title = "",              defval = color.aqua,   group = "S/R Levels", inline = "3")

finStyle = switch style

    "Dotted" => line.style_dotted
    "Dashed" => line.style_dashed
    =>          line.style_solid

type priceValues

    float higH
    float loW
    int   hiIndex
    int   loIndex

var pv = matrix.new<priceValues>(3, 4)

if barstate.isfirst

    for x = 0 to 2
        for i = 0 to 3

            value = switch

                i == 0 => priceValues.new(higH    =  0 )
                i == 1 => priceValues.new(loW     = 1e8)
                i == 2 => priceValues.new(hiIndex =  0 )
                i == 3 => priceValues.new(loIndex =  0 )

            pv.set(x, i, value)

method determine(float id, int A, int B, float C) =>
    id == C ? A : B

method append(matrix<priceValues> id, int length, int row) =>

    if barstate.islastconfirmedhistory

        for i = 0 to length

            id.set(row, 0, priceValues.new(higH    = math.max(math.avg(close[i], high[i]), nz(id.get(row, 0).higH, 0))))
            id.set(row, 2, priceValues.new(hiIndex = math.avg(close[i], high[i]).determine(math.round(time[i]), nz(id.get(row, 2).hiIndex, 0), id.get(row, 0).higH)))

            id.set(row, 1, priceValues.new(loW     = math.min(math.avg(close[i], low[i]), nz(id.get(row, 1).loW, 1e8))))
            id.set(row, 3, priceValues.new(loIndex = math.avg(close[i], low[i]).determine(math.round(time[i]), nz(id.get(row, 3).loIndex, 0), id.get(row, 1).loW)))

req(int length, int row) =>

    pv.append(length, row)
    loW     = pv.get(row, 1).loW
    higH    = pv.get(row, 0).higH
    hiIndex = pv.get(row, 2).hiIndex
    loIndex = pv.get(row, 3).loIndex

    [loW, higH, hiIndex, loIndex]

[min240S, min240R, min240Rtime, min240Stime]     = request.security(syminfo.tickerid, "240",  req(30, 0), lookahead = barmerge.lookahead_on)
[min1440S, min1440R, min1440Rtime, min1440Stime] = request.security(syminfo.tickerid, "1440", req(30, 1), lookahead = barmerge.lookahead_on)
[minWS, minWR, minWRtime, minWStime]             = request.security(syminfo.tickerid, "W",    req(15, 2), lookahead = barmerge.lookahead_on)

ex = switch extend

    "None"  => extend.none
    "Left"  => extend.left
    "Right" => extend.right
    "Both"  => extend.both

type objects

    line support
    line resistance

var obj = matrix.new<objects>(3, 2)

method condS(float id) => not na(id) and id != 1e8
method condR(float id) => not na(id) and id != 0

method lineSetSupport(matrix<objects> id, int row, int column, line ln) =>

    if not na(id.get(row, column))
        id.get(row, column).support.delete()

    id.set(row, column, objects.new(support = ln))

method lineSetResistance(matrix<objects> id, int row, int column, line ln) =>

    if not na(obj.get(row, column))
        obj.get(row, column).resistance.delete()

    id.set(row, column, objects.new(resistance = ln))

if barstate.islast

    if min240Show

        if min240S.condS()
            obj.lineSetSupport(0, 0, line.new(min240Stime, min240S, last_bar_time + (time - time[5]), min240S, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = min240col))

        if min240R.condR()
            obj.lineSetResistance(0, 1, line.new(min240Rtime, min240R, last_bar_time + (time - time[5]), min240R, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = min240col))

    if min1440Show

        if min1440S.condS()
            obj.lineSetSupport(1, 0, line.new(min1440Stime, min1440S, last_bar_time + (time - time[5]), min1440S, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = min1440col))

        if min1440R.condR()
            obj.lineSetResistance(1, 1, line.new(min1440Rtime, min1440R, last_bar_time + (time - time[5]), min1440R, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = min1440col))

    if minWShow

        if minWS.condS()
            obj.lineSetSupport(2, 0, line.new(minWStime, minWS, last_bar_time + (time - time[5]), minWS, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = minWcol))

        if minWR.condR()
            obj.lineSetResistance(2, 1, line.new(minWRtime, minWR, last_bar_time + (time - time[5]), minWR, extend = ex, xloc = xloc.bar_time, width = 1, style = finStyle, color = minWcol))

    res    = array.from("4 Hour: ♦", "Daily: ♦", "Weekly: ♦")
    resCol = array.from(min240col, min1440col, minWcol)

    valS = array.from(min240S, min1440S, minWS)
    valR = array.from(min240R, min1440R, minWR)

    var table tab = table.new(position.bottom_right, 10, 10, bgcolor = #20222C, border_color = #363843, frame_color = #363843, border_width = 1, frame_width = 1)

    tab.cell(1, 0, "Resolution", text_color = color.white), tab.cell(2, 0, "Support", text_color = color.white), tab.cell(3, 0, "Resistance", text_color = color.white)

    for i = 0 to 2

        tab.cell(1, i + 1, text = res.get(i), text_halign = text.align_right, text_size = size.small, text_color = resCol.get(i))

        finS = valS.get(i).condS() ? str.tostring(valS.get(i), format.mintick) : "Calculating"
        finR = valR.get(i).condR() ? str.tostring(valR.get(i), format.mintick) : "Calculating"

        tab.cell(2, i + 1, text = finS, text_size = size.small, text_color = resCol.get(i))
        tab.cell(3, i + 1, text = finR, text_size = size.small, text_color = resCol.get(i))

alertcondition(ta.crossover(high, min240R), "4-Hour Resistance Crossover", "4-Hour Resistance Crossover")
alertcondition(ta.crossunder(low, min240S), "4-Hour Support Crossunder", "4-Hour Support Crossunder")

alertcondition(ta.crossover(high, min1440R), "1-Day Resistance Crossover", "1-Day Resistance Crossover")
alertcondition(ta.crossunder(low, min1440S), "1-Day Support Crossunder", "1-Day Support Crossunder")

alertcondition(ta.crossover(high, minWR), "1-Week Resistance Crossover", "1-Week Resistance Crossover")
alertcondition(ta.crossunder(low, minWS), "1-Week Support Crossunder", "1-Week Support Crossunder")

var table dtTag = table.new(position.top_right, 1, 1)
if barstate.islast
    table.cell(dtTag, 0, 0, "@dailytrade", text_color = color.new(color.gray, 15), text_size = size.tiny, bgcolor = color.new(color.black, 100))
