//@version=5
indicator("Daily Trade | Order Blocks & Structure", shorttitle = "DT OB/Structure", overlay = true, max_labels_count = 500, max_lines_count = 500, max_boxes_count = 500, max_bars_back = 500)

bullC = input.color(defval = #14D990, title = "Bull Color", group = "Structure", inline = "1")
bearC = input.color(defval = #F24968, title = "Bear Color", group = "Structure", inline = "1")

showInt = input.bool(defval = true, title = "Show Internal Structure", group = "Structure")
intSens = input.int(3, "Internal Sensitivity", options = [3, 5, 8], group = "Structure")
intStru = input.string(defval = "All", title = "Internal Structure Type", options = ["All", "BoS", "CHoCH"], group = "Structure")

showExt = input.bool(defval = true, title = "Show External Structure", group = "Structure")
extSens = input.int(25, "External Sensitivity", options = [10, 25, 50], group = "Structure")
extStru = input.string(defval = "All", title = "External Structure Type", options = ["All", "BoS", "CHoCH"], group = "Structure")

showOB   = input.bool(defval = true, title = "Show Order Blocks", group = "Order Blocks")
showLast = input.int(defval = 10, title = "Order Blocks Count", minval = 0, group = "Order Blocks")

showHHLH = input.bool(defval = true, title = "Show HH / LH", group = "Swing Labels")
showHLLL = input.bool(defval = true, title = "Show HL / LL", group = "Swing Labels")

var highArr = array.new_float()
var lowArr  = array.new_float()

highArr.unshift(high)
lowArr.unshift(low)

calculatePivots(length) =>
    var int intraCalc = 0
    float topSwing = 0.0
    float botSwing = 0.0

    if bar_index > length + 1

        up = highArr.slice(0, length).max()
        dn = lowArr.slice(0, length).min()

        cHi = highArr.get(length)
        cLo = lowArr.get(length)

        intraCalc := switch

            cHi > up => 0
            cLo < dn => 1
            =>          intraCalc[1]

        topSwing := intraCalc == 0 and intraCalc[1] != 0 ? cHi : 0.0
        botSwing := intraCalc == 1 and intraCalc[1] != 1 ? cLo : 0.0

    [topSwing, botSwing]

[bigUpper, bigLower]     = calculatePivots(extSens)
[smallUpper, smallLower] = calculatePivots(intSens)

var box[] highBlock = array.new_box()
var box[] lowBlock  = array.new_box()

drawChar(x, y, str, col, down) =>
    style = down ? label.style_label_down : label.style_label_up
    line.new(int(x), y, bar_index, y, color = col, style = line.style_dashed)
    label.new(math.round(math.avg(x, bar_index)), y, str, color = #00000000, textcolor = col, style = style, size = size.small)

var float extUpAxis   = 0.0
var int   extUpAxis2  = 0
var int   extUpside   = 1
var float extDnAxis   = 0.0
var int   extDnAxis2  = 0
var int   extDownside = 1
var int   extMoving   = 0

drawStructureExt() =>
    var int counter = 0

    if bigUpper != 0
        extUpside := 1
        x1 = bar_index - extSens

        txt = bigUpper > extUpAxis ? 'HH' : 'LH'

        if showHHLH
            label.new(x1, bigUpper, txt, color = color.new(color.white, 100), textcolor = bearC, style = label.style_label_down, size = size.small)

        if showOB
            highBlock.push(box.new(x1, bigUpper, last_bar_index + 5, bigUpper * .998, border_color = color.new(color.red, 75), bgcolor = color.new(color.red, 95)))

        extUpAxis  := bigUpper
        extUpAxis2 := x1

        counter := 1

    if bigLower != 0
        extDownside := 1
        x1 = bar_index - extSens

        txt = bigLower < extDnAxis ? "LL" : "HL"

        if showHLLL
            label.new(x1, bigLower, txt, color = #ffffff00, textcolor = bullC, style = label.style_label_up, size = size.small)

        if showOB
            lowBlock.push(box.new(x1, bigLower, last_bar_index + 5, bigLower * 1.002, border_color = color.new(color.blue, 75), bgcolor = color.new(color.blue, 95)))

        extDnAxis  := bigLower
        extDnAxis2 := x1

        counter := -1

    if showExt
        if ta.crossover(close, extUpAxis)
            if extUpside != 0
                str = extMoving < 0 ? (extStru != "BoS" ? 'CHoCH' : "") : (extStru != 'CHoCH' ? 'BoS' : "")

                if extStru == "All" or str.contains(extStru, str)
                    drawChar(extUpAxis2, extUpAxis, str, bullC, true)

                extUpside := 0
                extMoving := 1

        if ta.crossunder(close, extDnAxis)
            if extDownside != 0
                str = extMoving > 0 ? (extStru != "BoS" ? 'CHoCH' : "") : (extStru != 'CHoCH' ? 'BoS' : "")

                if extStru == "All" or str.contains(extStru, str)
                    drawChar(extDnAxis2, extDnAxis, str, bearC, false)

                extDownside := 0
                extMoving   := -1

    counter

drawStructureExt()

method updateBox(array<box> id) =>
    if id.size() > 0
        for i = 0 to id.size() - 1
            id.get(i).set_right(last_bar_index + 5)

method cleanseLevel(array<box> id, bool isHighBlock) =>
    if id.size() > 0

        for i = id.size() - 1 to 0

            condition = isHighBlock ? close >= id.get(i).get_top() : close <= id.get(i).get_bottom()

            if condition
                id.remove(i).delete()

        if id.size() > showLast and showLast != 0
            for i = id.size() - showLast to 0
                id.remove(i).delete()

highBlock.cleanseLevel(true)
lowBlock.cleanseLevel(false)

if barstate.islast
    highBlock.updateBox()
    lowBlock.updateBox()

var float intUpAxis   = 0.0
var int   intUpAxis2  = 0
var int   intUpside   = 1
var float intDnAxis   = 0.0
var int   intDnAxis2  = 0
var int   intDownside = 1
var int   intMoving   = 0

drawStructureInternals() =>
    if showInt

        if smallUpper != 0
            intUpside  := 1
            intUpAxis  := smallUpper
            intUpAxis2 := bar_index - intSens

        if smallLower != 0
            intDownside := 1
            intDnAxis   := smallLower
            intDnAxis2  := bar_index - intSens

        if ta.crossover(close, intUpAxis)
            if intUpside != 0
                str = intMoving < 0 ? (intStru != "BoS" ? 'I-CHoCH' : "") : (intStru != "CHoCH" ? 'I-BoS' : "")

                if intStru == "All" or str.contains(str, intStru)
                    drawChar(intUpAxis2, intUpAxis, str, bullC, true)

                intUpside := 0
                intMoving := 1

        if ta.crossunder(close, intDnAxis)
            if intDownside != 0
                str = intMoving > 0 ? (intStru != "BoS" ? 'I-CHoCH' : "") : (intStru != "CHoCH" ? 'I-BoS' : "")

                if intStru == "All" or str.contains(str, intStru)
                    drawChar(intDnAxis2, intDnAxis, str, bearC, false)

                intDownside := 0
                intMoving   := -1

drawStructureInternals()

var table dtTag = table.new(position.top_right, 1, 1)
if barstate.islast
    table.cell(dtTag, 0, 0, "@dailytrade", text_color = color.new(color.gray, 15), text_size = size.tiny, bgcolor = color.new(color.black, 100))
